name: rotation_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  cupertino_icons: ^1.0.6
  latlong2: ^0.9.1
  json_annotation: ^4.9.0
  http: ^1.2.1
  auto_route: ^8.2.0
  permission_handler: ^11.3.1
  lottie: ^3.1.2
  logger: ^2.3.0
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/marker/
